#
# .travis.yml
# =============================================================================
# Reporter Multilang. Version 0.1
# =============================================================================
# A tool to generate human-readable reports based on data from various sources
# with the focus on its implementation using a series of programming languages.
#
# This is the configuration of the project characteristics
# used by the Travis CI (continuous integration) service
# to rebuild the project on every push and pull request.
#

%YAML 1.1
---

language: node_js

node_js:  "7"

sudo: required

dist: trusty

before_install:
    - sudo apt-get update

    ## Installing required Perl modules from CPAN.
    - sudo apt-get install cpanminus
    - sudo cpanm Try::Tiny DBI Text::TabularDisplay PDF::API2

    ## Installing required Python modules as Ubuntu packages.
    - sudo apt-get install python3-mysql.connector python3-psycopg2
                           python3-prettytable     python3-reportlab

    ## Installing the Vala compiler to build Vala/Genie impls.
    - sudo apt-get install valac

    ## Installing required Go packages from GitHub.
    - cd reporter-cli/sql-pdf/go && ls -al
      && GOPATH=`pwd` go get -u -v github.com/go-sql-driver/mysql
      && GOPATH=`pwd` go get -u -v github.com/lib/pq
      && GOPATH=`pwd` go get -u -v github.com/mattn/go-sqlite3
      && GOPATH=`pwd` go get -u -v github.com/jung-kurt/gofpdf
      && ls -al && cd -

    ##
    # Installing required JavaScript (Node.js) packages from npm,
    # and their respective prerequisites as Ubuntu packages.
    #
    - sudo apt-get install libgif-dev libpango1.0-dev
    - cd reporter-cli/sql-pdf/js && ls -al
      && npm install mysql pg sqlite3 sleep canvas
      && ls -al && cd -

script:
    ## TODO: Building all the packages under reporter-cli.
    - cd reporter-cli && ls -al

    ## TODO: Building all the packages under sql-pdf.
    - cd sql-pdf && ls -al

    ## Building the SQL to PDF reporter package as the Perl 5 (5.10+) impl.
    - cd perl && ls -al
              && make clean
              && make clean
              && ls -al
              && make all
              && make all
              && ls -al
              && ls -al bin lib src
              && ls -al
              && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Python 3 impl.
    - cd python && ls -al
                && make clean
                && make clean
                && ls -al
                && make all
                && make all
                && ls -al
                && ls -al bin lib src
                && ls -al
                && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Vala impl.
    - cd vala && ls -al
              && make clean
              && make clean
              && ls -al
              && make all
              && make all
              && ls -al
              && ls -al bin lib src
              && ls -al
              && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Genie impl.
    - cd genie && ls -al
               && make clean
               && make clean
               && ls -al
               && make all
               && make all
               && ls -al
               && ls -al bin lib src
               && ls -al
               && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Building the SQL to PDF reporter package as the Go impl.
    - cd go && ls -al
            && make clean
            && make clean
            && ls -al
            && make all
            && make all
            && ls -al 
            && ls -al bin lib obj src
            && ls -al
            && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ##
    # Building the SQL to PDF reporter package
    # as the JavaScript (ES5/Node.js) impl.
    #
    - cd js && ls -al
            && make clean
            && make clean
            && ls -al
            && make all
            && make all
            && ls -al
            && ls -al bin lib src
            && ls -al
            && echo

    ## Returning to the previous working dir.
    - cd - && ls -al

    ## Going one level up.
    - cd .. && ls -al

...

# vim:set nu:et:ts=4:sw=4:
